### ISSUE TITLE
Fix SONAME in Linux dynamic libraries

### ISSUE THREAD

**Issue by ao2** [macmade/makelib#3]
Right now the SONAME is not set correctly for Linux dynamic libraries:

```bash
$ cd Demo/
$ make
$ objdump -p Build/Debug/Products/x86_64/libFoo.so | grep SONAME
  SONAME               .so
```

It should have been:
```bash
$ objdump -p Build/Debug/Products/x86_64/libFoo.so | grep SONAME
  SONAME               libFoo.so
```

This seems to be caused by premature expansion of `$(PRODUCT_DYLIB)` in `Platform/Linux.mk`, a change like the following fixes it:

```diff
diff --git a/Platform/Linux.mk b/Platform/Linux.mk
index 3e2c8d9..209a14a 100644
--- a/Platform/Linux.mk
+++ b/Platform/Linux.mk
@@ -59,4 +59,4 @@ AR_FLAGS_$(HOST_ARCH)       := rcs
 CC_FLAGS_$(HOST_ARCH)       :=

 # Architecture specific flags for the C compiler when creating a dynamic library
-CC_FLAGS_DYLIB_$(HOST_ARCH) := -shared -Wl,-soname,$(PRODUCT_DYLIB)$(EXT_DYLIB)
+CC_FLAGS_DYLIB_$(HOST_ARCH) = -shared -Wl,-soname,$(PRODUCT_DYLIB)$(EXT_DYLIB)
```

I am not submitting a PR because you may probably want to review all your Make variables expansion and see if fixes are need in other places.

Ciao,
   Antonio

**Comment by macmade** [comment]
Thanks! I'll verify the other variables and let you known when this is fixed.
